name: Controllo Disponibilità Medico

on:
  schedule:
    - cron: "*/30 * * * *"  # Controllo ogni 30 minuti
  workflow_dispatch:  # 🔹 Aggiunto per avvio manuale

jobs:
  check_medico:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4 selenium

      - name: Run script
        run: python trova_medico.py
